### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by mapto** [thomas-de-jager/PRISMA-flow-diagram#1]
Hello, I find your code very useful. You haven't defined a license for it. Is it in the [public domain](https://en.wikipedia.org/wiki/Public_domain). If so, please specify it in a LICENSE file (github would guide you in the process in creating one). Otherwise, please indicate conditions of reuse. Thank you!

**Comment by thomas-de-jager** [comment]
Thanks for pointing this out. I'm not too familiar with this but the MIT license should be applicable. Added the license file
